### ISSUE TITLE
Add `<description>` tag to SVD file

### ISSUE THREAD

**Issue by xobs** [betrusted-io/betrusted-ec#14]
SVD files require a description of some sort. For example, Renode requires this in order to properly parse an SVD file.

For now we bodge the description in manually prior to adding the SVD file to Renode, but it would be nice if it were added automatically.

This can be accomplished by adding a `description` field: https://github.com/enjoy-digital/litex/blob/8e39060d268b8ab3cb07e917773f5aa8b5296801/litex/soc/integration/export.py#L363-L364

A `description="Betrusted EC"` argument can be appended to the `generate_svd()` function at https://github.com/betrusted-io/betrusted-ec/blob/main/betrusted_ec.py#L954

**Comment by bunnie** [comment]
I think this is what you wanted can you please confirm:

https://github.com/betrusted-io/betrusted-ec/commit/0f23bcb22c57ce1e342f6276fec2ce1bc68270ff

https://ci.betrusted.io/job/betrusted-ec/ws/build/software/soc.svd/*view*/

**Comment by xobs** [comment]
Yes, that's correct. Thank you!
